### ISSUE TITLE
Microsoft Edge not supported

### ISSUE THREAD

**Issue by Zireael** [fend25/strg.js#4]
Hi,
Strg seems to not work on Microsoft Edge (Windows 10) - I'm using v 41.16299.492.0
I've tried the /test page and JS fails. Tried on latest Chrome and I get test page working.

>  SCRIPT16389: Unspecified error.
> strg.min.js (1,16)
> 
>  SCRIPT5007: Unable to get property 'type' of undefined or null reference
> test.html (47,2)
>

**Comment by fend25** [comment]
Thank you for the attention and the issue!
And sorry fo so long answer.
Finally, I got to MS Edge browser and ran a test/index.html page.
So, in MS Edge 42.17134.1.0 (Microsoft EdgeHTML 17.17134) test page works well and all tests are in OK state (after page reload). Also, no any errors or warnings in the console.

Could you please check whether the problem is still?
If so, I will try to fix it.

![image](https://user-images.githubusercontent.com/4025269/55278731-1140db00-5321-11e9-9a0c-147b02c519ec.png)
